### ISSUE TITLE
 Hi, just wondering if this could be used to zoom out also (smaller image) - great work by the way

### ISSUE THREAD

**Issue by mrbobs** [Orbbloff/Godot-Magnifier-Shader#2]

**Comment by Orbbloff** [comment]
Hey! Yes, you can use the shader to zoom out by reducing the 'magnification' parameter below 1. But be very cautious, it get a little bit awkward when the magnification is really low. Thanks!

**Comment by mrbobs** [comment]
Thanks so much for getting back in touch so quickly - it works great.  For some reason I thought I must use negative numbers - which obviously gave some very strange results - Thanks again much appreciated.
